import {
  LOCALHOST1_ADDRESSES,
  LOCALHOST2_ADDRESSES,
  SEPOLIA_ADDRESSES,
  WLD_ADDRESSES,
  WLD_TESTNET_ADDRESSES,
} from './contract_addresses';
import { NETTYPE_1, NETTYPE_2, nettype } from './nettype';

// Swap network config

const NETTYPES = {
  testnet: WLD_TESTNET_ADDRESSES,
  mainnet: WLD_ADDRESSES,
};

export const MAPNETTOADDRESS = NETTYPES[nettype];

// Bridge network config

type NETWORKTOCHAIN = {
  [key: number]: ADDRESS_TYPE;
};

export const MAPNETWORKTOCHAINID: NETWORKTOCHAIN = {
  1: SEPOLIA_ADDRESSES,
  103: WLD_ADDRESSES,
  11155111: SEPOLIA_ADDRESSES,
  1337: LOCALHOST1_ADDRESSES,
  31337: LOCALHOST2_ADDRESSES,
  10395: WLD_TESTNET_ADDRESSES,
};

const NETTYPES_CHAIN1 = {
  ETHEREUM: SEPOLIA_ADDRESSES,
  WORLDLAND: WLD_ADDRESSES,
  WORLDLAND_TESTNET: WLD_TESTNET_ADDRESSES,
  SEPOLIA: SEPOLIA_ADDRESSES,
  LOCALHOST: LOCALHOST1_ADDRESSES,
};
const NETTYPES_CHAIN2 = {
  ETHEREUM: SEPOLIA_ADDRESSES,
  WORLDLAND: WLD_ADDRESSES,
  WORLDLAND_TESTNET: WLD_TESTNET_ADDRESSES,
  SEPOLIA: SEPOLIA_ADDRESSES,
  LOCALHOST: LOCALHOST2_ADDRESSES,
};

export const MAPNETTOADDRESS_CHAIN1 = NETTYPES_CHAIN1[NETTYPE_1];
export const MAPNETTOADDRESS_CHAIN2 = NETTYPES_CHAIN2[NETTYPE_2];
