import { LOCALHOST1_ADDRESSES, LOCALHOST2_ADDRESSES, SEPOLIA_ADDRESSES, WLD_ADDRESSES } from './contract_addresses';
import { nettype } from './nettype';

type NETWORKTOCHAIN = {
  [key: number]: ADDRESS_TYPE;
};

const NETTYPES = {
  testnet: SEPOLIA_ADDRESSES,
  mainnet: WLD_ADDRESSES,
};

export const MAPNETTOADDRESS = NETTYPES[nettype];

export const MAPNETWORKTOCHAINID: NETWORKTOCHAIN = {
  1: SEPOLIA_ADDRESSES,
  103: WLD_ADDRESSES,
  11155111: SEPOLIA_ADDRESSES,
  1337: LOCALHOST2_ADDRESSES,
  31337: LOCALHOST2_ADDRESSES,
};

const CHAIN_1 = 'SEPOLIA';
const CHAIN_2 = 'WORLDLAND';

const NETTYPES_CHAIN1 = {
  ETHEREUM: SEPOLIA_ADDRESSES,
  WORLDLAND: WLD_ADDRESSES,
  SEPOLIA: SEPOLIA_ADDRESSES,
  LOCALHOST: LOCALHOST1_ADDRESSES,
};
const NETTYPES_CHAIN2 = {
  ETHEREUM: SEPOLIA_ADDRESSES,
  WORLDLAND: WLD_ADDRESSES,
  SEPOLIA: SEPOLIA_ADDRESSES,
  LOCALHOST: LOCALHOST2_ADDRESSES,
};

export const MAPNETTOADDRESS_CHAIN1 = NETTYPES_CHAIN1[CHAIN_1];
export const MAPNETTOADDRESS_CHAIN2 = NETTYPES_CHAIN2[CHAIN_2];
