import { NETTYPE_1, NETTYPE_2 } from './nettype';

type ETHEREUM = 1;
type WORLDLAND = 103;
type WORLDLAND_TESTNET = 10395;
type SEPOLIA = 11155111;
type LOCALHOST_1 = 1337;
type LOCALHOST_2 = 31337;

type CHAIN_1 = ETHEREUM | WORLDLAND | LOCALHOST_1 | LOCALHOST_2 | SEPOLIA | WORLDLAND_TESTNET;
type CHAIN_2 = ETHEREUM | WORLDLAND | LOCALHOST_1 | LOCALHOST_2 | SEPOLIA | WORLDLAND_TESTNET;

type INETWORKTYPES = {
  ETHEREUM: ETHEREUM;
  WORLDLAND: WORLDLAND;
  WORLDLAND_TESTNET: WORLDLAND_TESTNET;
  SEPOLIA: SEPOLIA;
  LOCALHOST_1: LOCALHOST_1;
  LOCALHOST_2: LOCALHOST_2;
};

type INETWORKS = {
  CHAIN_1: CHAIN_1;
  CHAIN_2: CHAIN_2;
};

const NETWORKTYPES: INETWORKTYPES = {
  ETHEREUM: 1,
  WORLDLAND: 103,
  WORLDLAND_TESTNET: 10395,
  SEPOLIA: 11155111,
  LOCALHOST_1: 1337,
  LOCALHOST_2: 31337,
};

export const NETWORKS: INETWORKS = {
  CHAIN_1: NETWORKTYPES[NETTYPE_1],
  CHAIN_2: NETWORKTYPES[NETTYPE_2],
};
