export const PATH = {
  MAIN: '/',
  LEARN: '/learn',
  LEARN_OVERVIEW: '/learn/overview',
  LEARN_ECCPOW: '/learn/eccpow',
  LEARN_ASIC_RESISTENCE: '/learn/asic-resistence',
  LEARN_PQ_SECURITY: '/learn/pq-security',
  LEARN_GREEN_VCA: '/learn/green-vca',
  LEARN_DESIGN_PRINCIPLE: '/learn/design-principle',
  LEARN_HOW_WORKS: '/learn/how-works',
  LEARN_COINOMICS: '/learn/coinomics',
  LEARN_GOVERNANCE: '/learn/governance',
  LEARN_FAQ: '/learn/faq',
  SWAP: '/swap',
  POOL: '/pool',
  ADD: '/pool/add-liquidity',
};
