export enum ABI {
  ETHEREUM_BRIDGE_ABI = 'ETHEREUM_BRIDGE_ABI',
  POLYGON_BRIDGE_ABI = 'POLYGON_BRIDGE_ABI',
  ERC20_ABI = 'ERC20_ABI',
  UNISWAPV2_ROUTER = 'UNISWAPV2_ROUTER',
  UNISWAPV2_PAIR = 'UNISWAPV2_PAIR',
  UNISWAPV2_FACTORY = 'UNISWAPV2_FACTORY',
  ETH_TOKEN_ADDRESS = 'ETH_TOKEN_ADDRESS',
  DAI_TOKEN_ADDRESS = 'DAI_TOKEN_ADDRESS',
  WRAPETH = 'WRAPETH',
  LVSWAPV2_ROUTER = 'LVSWAPV2_ROUTER',
  LVSWAPV2_FACTORY = 'LVSWAPV2_FACTORY',
}

export enum Field {
  INPUT = 'INPUT',
  OUTPUT = 'OUTPUT',
}

export enum CONTRACT_ADDRESSES {
  ETH_ADDRESSES = 'ETH_ADDRESSES',
  WLD_ADDRESSES = 'WLD_ADDRESSES',
  WRAPPEDETH_ADDRESS_BRIDGE = 'WRAPPEDETH_ADDRESS_BRIDGE',
  BRIDGE_CONTRACT = 'BRIDGE_CONTRACT',
  TOKEN_CONTRACT = 'TOKEN_CONTRACT',
  WRAPPEDETH_ADDRESS = 'WRAPPEDETH_ADDRESS',
  LVT_ADDRESS = 'LVT_ADDRESS',
  UNISWAP = 'UNISWAP',
  FACTORY = 'FACTORY',
  PAIR = 'PAIR',
  PAIRS = 'PAIRS',
  ROUTER = 'ROUTER',
  LP_TOKEN_ADDRESS = 'LP_TOKEN_ADDRESS',
  ETH_TOKEN_ADDRESS = 'ETH_TOKEN_ADDRESS',
  DAI_TOKEN_ADDRESS = 'DAI_TOKEN_ADDRESS',
  TOKENA = 'TOKENA',
  TOKENB = 'TOKENB',
  ERC20_ABI = 'ERC20_ABI',
}

export enum FUNCTION {
  GETAMOUNTOUT = 'getAmountOut',
  GETAMOUNTSOUT = 'getAmountsOut',
  BURN = 'BURN',
  SWAPEXACTTOKENSFORTOKENS = 'swapExactTokensForTokens',
}

export enum CHAINDS {
  WORLDLAND_SEOUL = 'WORLDLAND_SEOUL',
  WORLDLAND_GWANGJU = 'WORLDLAND_GWANGJU',
}

export enum TOKEN {
  SYMBOL = 'symbol',
  TITLE = 'title',
  ICON = 'icon',
  AMOUNT = 'amount',
  ADDRESS = 'address',
}
