export enum ABI {
  ETHEREUM_BRIDGE_ABI = 'ETHEREUM_BRIDGE_ABI',
  POLYGON_BRIDGE_ABI = 'POLYGON_BRIDGE_ABI',
  ERC20_ABI = 'ERC20_ABI',
  UNISWAPV2_ROUTER = 'UNISWAPV2_ROUTER',
  UNISWAPV2_PAIR = 'UNISWAPV2_PAIR',
  UNISWAPV2_FACTORY = 'UNISWAPV2_FACTORY',
  DAI_ADDRESS = 'DAI_ADDRESS',
  WRAPPEDETH = 'WRAPPEDETH',
  LVSWAPV2_ROUTER = 'LVSWAPV2_ROUTER',
  LVSWAPV2_FACTORY = 'LVSWAPV2_FACTORY',
  LVSWAPV2_PAIR = 'LVSWAPV2_PAIR',
  BRIDGEBASE_ABI = 'BRIDGEBASE_ABI',
  AWARD_LINEAR_TIMELOCK = 'AWARD_LINEAR_TIMELOCK',
  ERC721_WNFTMINTER = 'ERC721_WNFTMINTER',
}

export enum Field {
  INPUT = 'INPUT',
  OUTPUT = 'OUTPUT',
}

export enum CONTRACT_ADDRESSES {
  ETH_ADDRESSES = 'ETH_ADDRESSES',
  WLD_ADDRESSES = 'WLD_ADDRESSES',
  WRAPPEDETH_ADDRESS_BRIDGE = 'WRAPPEDETH_ADDRESS_BRIDGE',
  BRIDGE_CONTRACT = 'BRIDGE_CONTRACT',
  TOKEN_CONTRACT = 'TOKEN_CONTRACT',
  WWLC_ADDRESS = 'WWLC_ADDRESS',
  LVT_ADDRESS = 'LVT_ADDRESS',
  UNISWAP = 'UNISWAP',
  FACTORY = 'FACTORY',
  PAIR = 'PAIR',
  PAIRS = 'PAIRS',
  ROUTER = 'ROUTER',
  WETH_ADDRESS = 'WETH_ADDRESS',
  ETH_ADDRESS = 'ETH_ADDRESS',
  WLC_ADDRESS = 'WLC_ADDRESS',
  LP_TOKEN_ADDRESS = 'LP_TOKEN_ADDRESS',
  DAI_ADDRESS = 'DAI_ADDRESS',
  ERC20_ABI = 'ERC20_ABI',
  BRIDGE = 'BRIDGE',
  AWARD_LINEAR_TIMELOCK = 'AWARD_LINEAR_TIMELOCK',
  ERC721_WNFTMINTER = 'ERC721_WNFTMINTER',
}

export enum FUNCTION {
  ADDLIQUIDITY = 'addLiquidity',
  ADDLIQUIDITYETH = 'addLiquidityETH',
  REMOVELIQUIDITY = 'removeLiquidity',
  APPROVE = 'approve',
  GETAMOUNTOUT = 'getAmountOut',
  GETAMOUNTSOUT = 'getAmountsOut',
  GETMARKETPRICE = 'getMarketPrice',
  GETPAIR = 'getPair',
  BURN = 'BURN',
  SWAPEXACTETHFORTOKENS = 'swapExactETHForTokens',
  SWAPEXACTTOKENSFORTOKENS = 'swapExactTokensForTokens',
  TOKEN0 = 'token0',
  TOKEN1 = 'token1',
  TOTALSUPPLY = 'totalSupply',
  TRANSFER = 'transfer',
  GETRESERVES = 'getReserves',
  LOCKETH = 'lockETH',
  BURNWETH = 'burnWETH',
  LOCKTOKEN = 'lockToken',
  BURNTOKEN = 'burnToken',
  SETTIMESTAMP = 'setTimestamp',
  BULKDEPOSITTOKENSFEATURINGTIMESTAMP = 'bulkDepositTokensFeaturingTimestamp',
  FINALIZE = 'finalizeAllIncomingDeposits',
  DEPOSITWL = 'depositWL',
  WITHDRAWWL = 'withdrawEth',
  WITHDRAW = 'transferTimeLockedTokensAfterTimePeriod',
}

export enum QUERY {
  ALLOWANCE = 'allowance',
  BALANCEOF = 'balanceOf',
  TIMESTAMPISSET = 'timestampSet',
  CONTRACTBALANCE = 'contractBalance',
  GETAVAILAMOUNT = 'getAvailAmount',
  CLIFFEDGE = 'cliffEdge',
  RELEASEEDGE = 'releaseEdge',
  TIMEPERIODS = 'timePeriods',
  ISFINALISED = 'allIncomingDepositsFinalised',
  OWNER = 'owner',
  BALANCES = 'balances',
}

export enum CHAINDS {
  WORLDLAND = 'worldland',
  WORLDLAND_TESTNET = 'worldland_testnet',
}

export enum TOKEN {
  SYMBOL = 'symbol',
  TITLE = 'title',
  ICON = 'icon',
  AMOUNT = 'amount',
  ADDRESS = 'address',
}

export enum ACTIONS {
  FETCH_AMOUNT_OUT_REQUEST = 'FETCH_AMOUNT_OUT_REQUEST',
  FETCH_AMOUNT_OUT_SUCCESS = 'FETCH_AMOUNT_OUT_SUCCESS',
  FETCH_AMOUNT_OUT_FAILURE = 'FETCH_AMOUNT_OUT_FAILURE',
}
